### PR TITLE
Add stagedOnly option and upgrade dependencies

### PR DESCRIPTION
**Pull request by disovi**

### CODE REVIEW

**Comment by disovi** [comment]
Well, either node version should be updated in travis, or dependencies should be downgraded, up to maintainer.

**Comment by mikaelbr** [comment]
👍 Feel free to bump version on travis

**Comment by mikaelbr** [comment]
Thanks 🍰 I've added you as a collaborator if you want to do some more changes. Just let me know when/what/if I should publish. Or I can add you to NPM

**Comment by disovi** [comment]
Thank you for fast review ;)

**Comment by mikaelbr** [comment]
Sure thing!

```
gulp-gitmodified@1.2.0
```

**Pull request merged**
