### PR TITLE
Fix for console log undefined when there is no gitCwd

### PR DESCRIPTION
**Pull request by alexdrimbe**

### CODE REVIEW

**Comment by maxlapides** [comment]
awesome project! would love to see this PR merged in :)

**Comment by mikaelbr** [comment]
Hi. Sorry, this one fell through the cracks. This `console.log` shouldn't be there at all. I'm merging this and fixing it. Thanks for letting me know :+1:

**Comment by maxlapides** [comment]
yay! so fast! thanks a ton!

**Comment by mikaelbr** [comment]
```
➜  gulp-gitmodified git:(master) npm publish
+ gulp-gitmodified@1.1.1
```
:tada:

**Pull request merged**
